In [ ]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 1.8 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [ ]:
import sqlalchemy as sqla
import pymysql
import pandas as pd

db =sqla.create_engine('mysql+pymysql://mnaTC4029User:mnaTC4029Pass:@20.106.157.52:3306/MOVIES',pool_recycle=3600)

conn = db.connect

In [ ]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine('mysql+pymysql://mnaTC4029User:mnaTC4029Pass!@20.51.200.131:3306/Netflix', pool_recycle=3600)
conn = db.connect()

In [ ]:
query = sqla.text('SELECT * FROM view_summary LIMIT 100')
df = pd.read_sql(query, db)
df

,id,created_date,modified_date,cumulative_weeks_in_top10,duration,end_date,hours_viewed,start_date,view_rank,views,movie_id,season_id
0,1,2024-01-01,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,263700000,2024-01-01,NaN,143800000,1,None
1,2,2024-01-01,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,230800000,2024-01-01,NaN,129400000,2,None
2,3,2024-01-01,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,252500000,2024-01-01,NaN,103800000,3,None
3,4,2024-01-01,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,146800000,2024-01-01,NaN,84700000,4,None
4,5,2024-01-01,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,123100000,2024-01-01,NaN,80300000,5,None
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2024-01-01,2024-01-01,8.0,WEEKLY,2024-05-26,2400000,2024-05-20,10.0,1400000,20,None
96,97,2024-01-01,2024-01-01,7.0,WEEKLY,2024-05-19,2300000,2024-05-13,10.0,1300000,20,None
97,98,2024-01-01,2024-01-01,6.0,WEEKLY,2024-05-12,2200000,2024-05-06,10.0,1300000,20,None
98,99,2024-01-01,2024-01-01,5.0,WEEKLY,2024-05-05,3400000,2024-04-29,5.0,1900000,20,None
99,100,2024-01-01,2024-01-01,4.0,WEEKLY,2024-04-28,5400000,2024-04-22,4.0,3100000,20,None

In [ ]:
query = sqla.text("""
  SELECT * FROM movie
  WHERE runtime > 300
""")
pd.read_sql(query, conn)

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,5793,2024-01-01,2024-01-01,b'\x00',None,日本統一シリーズ: 映画シリーズ,None,3892,Nihontouitsu Series: Film Series
1,5794,2024-01-01,2024-01-01,b'\x00',None,釣りバカ日誌: 映画シリーズ,None,2120,Free and Easy Series: Film Series
2,5874,2024-01-01,2024-01-01,b'\x01',None,None,2021-08-06,312,Navarasa: Limited Series
3,9729,2024-01-01,2024-01-01,b'\x00',None,織田同志会 織田征仁: 映画シリーズ,None,710,Seiji Oda: Film Series
4,9730,2024-01-01,2024-01-01,b'\x00',None,キングダム～首領になった男～: 映画シリーズ,None,427,Kingdom ~ The Man Who Became the Top ~: Film S...

In [ ]:
query = sqla.text("""
  SELECT COUNT(*) AS total,
         SUM(CASE WHEN locale = 'US' THEN 1 ELSE 0 END) AS solo_us
  FROM movie
  WHERE locale IS NOT NULL
""")
df = pd.read_sql(query, conn)
(df['solo_us'][0] / df['total'][0]) * 100

np.float64(0.0)